#pragma once

#include <postgres/Client.h>
#include <postgres/Command.h>
#include <postgres/Config.h>
#include <postgres/Connection.h>
#include <postgres/Consumer.h>
#include <postgres/Context.h>
#include <postgres/Error.h>
#include <postgres/Field.h>
#include <postgres/Oid.h>
#include <postgres/PreparedCommand.h>
#include <postgres/PrepareData.h>
#include <postgres/Receiver.h>
#include <postgres/Result.h>
#include <postgres/Row.h>
#include <postgres/Statement.h>
#include <postgres/Status.h>
#include <postgres/Time.h>
#include <postgres/Transaction.h>
#include <postgres/Visitable.h>
